### ISSUE TITLE
Can RedBPF programs be loaded without cargo?

### ISSUE THREAD

**Issue by TheOnlyArtz** [redsift/redbpf#100]
Hey, I've followed and compiled the example in the cargo-bpf docs (to block port 80)

I'm running an OpenWRT instance and I've tried to load the `.elf` file using 
`ip link set dev eth0 xdp obj block_http.elf`
And I'm getting `Error fetching program/map!` 

Maybe the compiled program isn't compiled for the right architecture? what can cause that? maybe I'm loading it wrong

**Comment by neallred** [comment]
Having the same issue. Running on a vagrant VM with fedora 33, kernel version 5.8.15-301.fc33.x86_64, with cargo version 1.47.0, cargo-bpf 1.2.0, redbpf-macros 1.2.0 and redbpf-probes 1.2.0. I'm running

`ip link set dev eth0 xdp obj <path to elf file> sec xdp/xdp_program`

I'm also still getting `Error fetching program/map!`

`man ip link` has some helpful info on loading XDP programs, under the `ip link set` section, especially the `xdp` option.

From what I can tell from that doc, we need to give a `sec` option because the elf file redbpf generates names the program section `elf/<whatever you named the function with the #[xdp] macro>`. You can check the section names in your elf file with readelf -S <path to elf file>.

**Comment by rsdy** [comment]
I think the issue is that we're not compatible with libbpf, and therefore `ip` and `tc` will not work without some hacks. Try post-processing your probe as a workaround, like @aquarhead did it [here](https://github.com/aquarhead/protect-the-rabbit/blob/master/Makefile.toml#L11). This is something we will need to address at some point in `cargo-bpf`, though.

**Comment by aquarhead** [comment]
If you're loading XDP you can also bundle the BPF program into a single binary, and you will only need to deploy/run this single binary to load it (and don't even need to post-process the BPF ELF program).

I explored this idea in [this project](https://github.com/aquarhead/ready-to-rabbit), so the final deployable includes the raw BPF ELF bytes [here](https://github.com/aquarhead/ready-to-rabbit/blob/dbc04351c643bb62f58c3a2d6379c4c4cba367a9/src/main.rs#L15) and [use RedBPF functions to attach it](https://github.com/aquarhead/ready-to-rabbit/blob/dbc04351c643bb62f58c3a2d6379c4c4cba367a9/src/main.rs#L30) the outer loop is a rather naive method to discover all network interfaces. The whole process is also captured in [a cargo-make file](https://github.com/aquarhead/ready-to-rabbit/blob/dbc04351c643bb62f58c3a2d6379c4c4cba367a9/Makefile.toml) the strip is only there as an attempt to reduce deployable size (I don't think it changed much, for whatever reason) and it's not necessary iirc.

**Comment by neallred** [comment]
@rsdy the workaround from @aquarhead works. I made a minimal repro for anyone else running into this that wants to use the `ip` cli: https://git.sr.ht/~neallred/bug-repros/tree/master/item/redbpf-postprocessing

**Comment by neallred** [comment]
@aquarhead I like it! I'm going to have to poke around with my project to see if I can do something similar.

**Comment by aquarhead** [comment]
@neallred neat repo :) BTW my XDP attach code are mostly extracted from `cargo-bpf`, it mainly shows an idea to do single binary deployment :)

**Comment by TheOnlyArtz** [comment]
Hey! I wanted to tell you that it is working indeed! The only issue which is unrelated seems to be OpenWRT's luck of support in XDP BPF programs, but I've loaded a program successfully on Ubuntu!

**Comment by TheOnlyArtz** [comment]
Do you guys know whether the compiled ELF program can be loaded on different Distros? 
I've compiled the block_http on an Ubuntu 18.04 and I'm not trying to load it on an Ubuntu Server 18.04 the same way I've loaded on the non server one, and for some reason I get an error says `Cannot initialize ELF context!`, Maybe it has something to do with the kernel headers?
