### ISSUE TITLE
Purpose of libbpf and bcc/libbpf?

### ISSUE THREAD

**Issue by kbknapp** [redsift/redbpf#109]
First, thanks for these libraries and the work you've put into them! I know I've been posting a bunch of issues :smile:

Would it be possible to add some documentation on the structure of bpf-sys? I've been diving into bpf-sys as well as [libbpf/libbpf-rs](https://github.com/libbpf/libbpf-rs) to get a full feel of BPF code in Rust. 

NB. the biggest headache that exists right now (IMO) is the dichotomy between `iproute2` (`ip`/`tc`) loaders/maps as well as `libbpf`, and how that dichotomy plays out in the various Rust libraries.

While going through the `bpf-sys` I saw that `libbpf` is a submodule, but BCC's `libbpf` is also included as just a copy/paste import however upstream BCC uses a submodule for its `libbpf` as well. Why not just use the `libbpf` submodule from upstream?

**Comment by alessandrod** [comment]
The reason for having both the libbpf submodule and BCC's libbpf is pretty much historical. When bpf-sys was first written libbpf was very unstable and the BCC libbpf wrapper was somewhat more stable so bpf-sys was written to use the latter. 

Around a year ago I added the libbpf submodule and started generating the rust BPF helpers from it. I didn't get rid of the BCC libbpf wrapper tho because it contained workarounds for older kernel versions. So now we use the libbpf submodule to generate the BPF helpers and low level BPF data structures, and bpf-sys uses the BCC wrapper to load the programs, maps etc.

Now that libbpf has matured and we don't support ancient kernels anymore, we should update the libbpf module, remove the BCC wrapper, and switch bpf-sys to using libbpf directly.

**Comment by kbknapp** [comment]
Thanks for the explanation that helped a ton!

**Comment by belltoy** [comment]
Any plan for this?

> Now that libbpf has matured and we don't support ancient kernels anymore, we should update the libbpf module, remove the BCC wrapper, and switch bpf-sys to using libbpf directly.

**Comment by rhdxmr** [comment]
Because I am a relatively new member of redbpf, so I am confused when I run into the design which is based on historical reasons.
What do you think of this, @rsdy?
Does it feel OK to remove BCC wrapper as @alessandrod said before?
If it looks OK, I will give it a shot.

**Comment by rsdy** [comment]
There's nothing theoretically preventing us to do this, but I would imagine it's not a small piece of work. Some compiler driven development might be needed to find the right APIs that need replacing.

**Comment by rhdxmr** [comment]
> There's nothing theoretically preventing us to do this, but I would imagine it's not a small piece of work. Some compiler driven development might be needed to find the right APIs that need replacing.

oh no, that's scary..

**Comment by belltoy** [comment]
I have took a glance at the differences between bcc and libbpf.

The wrapper API of libbpf in bcc are less strict, eg. the args of `bpf_*_elem` are lack of `const`. These should be replaced by the version of libbpf. And I think that's not too much work.

But bcc provides some other helpers functions which are not provided by libbpf. For example `perf_reader` helpers and some  `bpf_attch_*` helpers. I think we can get rid of those implemetations with pure rust impl instead.

BTW, the ref of libbpf submodule is far behind the upstream version, and bcc maybe as well.
