### ISSUE TITLE
Examples for redbpf

### ISSUE THREAD

**Issue by fristonio** [redsift/redbpf#3]
It would be great if we can have some example programs for using `redbpf` implementing some elementary ones from https://github.com/iovisor/bcc/tree/master/examples

**Comment by rsdy** [comment]
A full-blown daemon using redbpf is [ingraind](https://github.com/redsift/ingraind).

The [`bpf`](https://github.com/redsift/ingraind/tree/master/bpf) folder in the repo has the BPF code, while the rust-side is at [`src/grains`](https://github.com/redsift/ingraind/tree/master/src/grains).

In reality, there's quite a lot of [plumbing](https://github.com/redsift/ingraind/blob/master/src/grains/ebpf.rs) that's necessary to make redbpf useful, because in contrast to BCC the design is for [pre-compiling](https://github.com/redsift/ingraind/blob/master/build.rs#L12) the BPF code.

After the plumbing is done, a simple probe's implementation is [fairly minimal](https://github.com/redsift/ingraind/blob/master/src/grains/syscalls.rs).

I think, depending on what you're aiming to do, using ingraind as a framework might be a better call than building on the low-level lib that is redbpf.

**Comment by rsdy** [comment]
Resolved by #48
