### ISSUE TITLE
redbpf-iotop in redbpf-tools panics with a ParseError(Map)

### ISSUE THREAD

**Issue by jeromegn** [redsift/redbpf#60]
Not entirely sure how to fix this, the error doesn't give more information.

```
$ uname -a
Linux arch 5.5.13-arch2-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64 GNU/Linux
```

```
$ rustc --version
rustc 1.42.0 (b8cedc004 2020-03-09)
```

**Comment by wfchandler** [comment]
This is probably occurring because the `redbpf-iotop` was not run with root access, but the error message is not providing much help in discovering this.

In this scenario [maps.insert](https://github.com/redsift/redbpf/blob/9d4b300416f6d21c7307dad546c899457c8347b7/redbpf/src/lib.rs#L538) returns `ParseError::Map` because the `bpf(BPF_MAP_CREATE, ...)` syscall fails with `EPERM`.

`strace` makes this easier to see:

```
01:45:01.811647 bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_HASH, key_size=8, value_size=8, max_entries=10240, map_flags=0, inner_map_fd=0</dev/pts/2<char 136:2>>, map_name="start", map_ifindex=0, btf_fd=0</dev/pts/2<char 136:2>>, btf_key_type_id=0, btf_value_type_id=0, btf_vmlinux_value_type_id=0}, 112) = -1 EPERM (Operation not permitted) <0.000352>
01:45:01.813446 write(2</dev/pts/2<char 136:2>>, "thread '", 8thread ') = 8 <0.000095>
01:45:01.813708 write(2</dev/pts/2<char 136:2>>, "main", 4main) = 4 <0.000093>
01:45:01.813965 write(2</dev/pts/2<char 136:2>>, "' panicked at '", 15' panicked at ') = 15 <0.000182>
01:45:01.814354 write(2</dev/pts/2<char 136:2>>, "error loading probe: ParseError(Map)", 36error loading probe: ParseError(Map)) = 36 <0.000123>
```

However, even when running with `sudo` this still panics on my machine with `cannot attach kprobe, probe entry may not exist`.  I've opened #85 for that issue.

**Comment by rsdy** [comment]
@wfchandler is correct, you must run these tools as root. I added a better error message if you're trying to run `redbpf-tools` stuff as a user.
