### ISSUE TITLE
How do I add tracepoints

### ISSUE THREAD

**Issue by purpleP** [redsift/redbpf#62]
I'm learning about ebpf with a Linux Observability with epbf

https://github.com/bpftools/linux-observability-with-bpf/blob/master/code/chapter-2/hello_world/bpf_program.c

I wonder how to port this example to rust? I really wouldn't want to deal with C if possible (or go for that matter).

**Comment by rsdy** [comment]
One example of attaching to a syscall can be found in ingraind: https://github.com/redsift/ingraind/blob/master/ingraind-probes/src/syscalls/main.rs

If you specifically look for tracepoints, they are also available, although we don't have the proc macro interface fleshed out for them. https://ingraind.org/api/redbpf/struct.TracePoint.html

In practice, I would always use kprobes over tracepoints, though, since there's little difference between them in practice, and they can be used in similar situations.

Let me know if you run into any issues.

**Comment by purpleP** [comment]
@rsdy `use ingraind_probes::syscalls::SyscallTracepoint;` `ingraind_probes` doesn't seem to be available on crates.io. If seems like epbf in rust status is "half-baked". Or am I doing something wrong?

**Comment by rsdy** [comment]
`ingraind_probes` is not usable independently, and therefore it's not available on crates.io. The line you're trying to `use` is just a struct that is used to communicate with userspace. There's nothing special about it.

https://ingraind.org/api/redbpf_probes/kprobe/index.html this is how you would write the probe you want for x86_64:

```
#![no_std]
#![no_main]
use redbpf_probes::kprobe::prelude::*;

program!(0xFFFFFFFE, "GPL");

#[kprobe("__x64_sys_")]
pub fn enter_execve(regs: Registers) {
    // do something here
    // ...
}
```

Read https://ingraind.org/api/cargo_bpf/index.html to learn how to run this program using `cargo bpf`. You will not need anything from the ingraind repository. Sorry about the confusion in my previous comment.

**Comment by wintermanc3r** [comment]
@rsdy Would you mind elaborating a bit on why you'd rather use kprobes? Tracepoints seem like an obvious choice for something long running/light weight (portable, supposedly faster and more performant than kprobes?) and I'm just trying to make sure I'm not missing anything obvious before taking a look at the work involved for full proc_macro support for tracepoints...
