### ISSUE TITLE
License consideration

### ISSUE THREAD

**Issue by sdbrain** [redsift/redbpf#8]
Firstly, Thanks for this awesome library.. been wanting to use rust to develop user space application for eBPF/XDP. would you consider using a more permissive license so that the library can be adopted more widely. In most companies, GPL v3 is a non starter. Adding a more permissive license could also attract more contributions.

Thanks again for the awesome contribution to the rust community!

**Comment by rsdy** [comment]
Thanks for bringing this up again. We're getting a lot of questions about this, and the answer is it's GPLv3 because it was easy, and certain eBPF programs need to be GPL to be useful at all.

That said, we're looking at what needs to be done to re-license under Apache2/MIT, and I hope we can release a version under more permissive licenses within a few weeks. Will update here on the progress.

**Comment by sdbrain** [comment]
Thanks for considering the request..

**Comment by rsdy** [comment]
@sdbrain I just merged the relicensing with #14 . I will release a new version shortly, but until then, you can already use master.

**Comment by sdbrain** [comment]
thanks!
